# action panel
fps = 'FPS '
speed = 'Speed'
accrue = 'Accrue'
falloff = 'Falloff'
type_fx = 'Type FX'
start_bone = 'Start Bone'
power = 'Power '
bone_part = 'Bone Part'
stop = ' Stop '
no_mix = 'No Mix'
sync = 'Sync'
foot_steps = 'Foot Steps'
move_xform = 'Move XForm'
idle = 'Idle'
weapon_bone = 'Weapon Bone'
settings = 'Settings'
bake = 'Bake'
use_custom_thresh = 'Use Custom Thresholds'
loc_thresh = 'Location Threshold'
rot_thresh = 'Rotation Threshold'
export_skl = 'Export .skl'

# armature panel
display_bone_shapes = 'Display Bone Shapes'
display_bone_mass_centers = 'Display Bone Mass Centers'
crosshair_size = 'Сrosshair Size'
display_bone_limits = 'Display Bone Limits'
gizmo_radius = 'Gizmo Radius'
limit_x = 'Limit X'
limit_y = 'Limit Y'
limit_z = 'Limit Z'
use_limits = 'Use Limits'
