# action panel
fps = 'FPS '
speed = 'Speed'
accrue = 'Accrue'
falloff = 'Falloff'
type_fx = 'Type FX'
start_bone = 'Start Bone'
power = 'Power '
bone_part = 'Bone Part'
stop = ' Stop '
no_mix = 'No Mix'
sync = 'Sync'
foot_steps = 'Foot Steps'
move_xform = 'Move XForm'
idle = 'Idle'
weapon_bone = 'Weapon Bone'
settings = 'Settings'
bake = 'Bake'
use_custom_thresh = 'Use Custom Thresholds'
loc_thresh = 'Location Threshold'
rot_thresh = 'Rotation Threshold'
export_skl = 'Export .skl'
on = 'On'

# armature panel
display_bone_shapes = 'Display Bone Shapes'
display_bone_mass_centers = 'Display Bone Mass Centers'
crosshair_size = 'Сrosshair Size'
display_bone_limits = 'Display Bone Limits'
gizmo_radius = 'Gizmo Radius'
limit_x = 'Limit X'
limit_y = 'Limit Y'
limit_z = 'Limit Z'
use_limits = 'Use Limits'

# bone panel
exportable = 'Exportable'
material = 'Material'
length = 'Length'
shape_type = 'Shape Type'
shape_id = 'Shape ID'
no_pickable = 'No Pickable'
no_physics = 'No Physics'
remove_after_break = 'Remove After Break'
no_fog_collider = 'No Fog Collider'
joint_type = 'Joint Type'
friction = 'Friction'
spring = 'Spring'
damping = 'Damping '
minimum = 'Min'
maximum = 'Max'
steer = 'Steer'
steer_roll = 'Steer-X / Roll-Z'
rotate_z = 'Rotate Z'
slide_z = 'Slide Z'
joint_id = 'Joint ID'
breakable = 'Breakable'
force = 'Force'
torque = 'Torque'
edit_center = 'Edit Center'
edit_shape = 'Edit Shape'
rigid = 'Rigid'
joint = 'Joint'
wheel = 'Wheel '
slider = 'Slider '
custom = 'Custom '

# edit helper
cancel = 'Cancel'
apply_shape = 'Apply Shape'
fit_shape = 'Fit Shape'
apply_center = 'Apply Center'
align_center = 'Align Center'
