# level collection names
LEVEL_MAIN_COLLECTION_NAME = 'Level'
LEVEL_VISUALS_COLLECTION_NAME = 'Visuals'
LEVEL_CFORM_COLLECTION_NAME = 'CForm'
LEVEL_GLOWS_COLLECTION_NAME = 'Glows'
LEVEL_LIGHTS_COLLECTION_NAME = 'Lights'
LEVEL_PORTALS_COLLECTION_NAME = 'Portals'
LEVEL_SECTORS_COLLECTION_NAME = 'Sectors'

LEVEL_COLLECTION_NAMES = (
    LEVEL_VISUALS_COLLECTION_NAME,
    LEVEL_CFORM_COLLECTION_NAME,
    LEVEL_GLOWS_COLLECTION_NAME,
    LEVEL_LIGHTS_COLLECTION_NAME,
    LEVEL_PORTALS_COLLECTION_NAME,
    LEVEL_SECTORS_COLLECTION_NAME
)

# visuals collection names
LEVEL_VISUALS_NORMAL_COLLECTION_NAME = 'Normal'
LEVEL_VISUALS_HIERRARHY_COLLECTION_NAME = 'Hierrarhy'
LEVEL_VISUALS_PROGRESSIVE_COLLECTION_NAME = 'Progressive'
LEVEL_VISUALS_LOD_COLLECTION_NAME = 'LoD'
LEVEL_VISUALS_TREE_PM_COLLECTION_NAME = 'Tree Progressive'
LEVEL_VISUALS_TREE_ST_COLLECTION_NAME = 'Tree Static'

LEVEL_VISUALS_COLLECTION_NAMES = (
    LEVEL_VISUALS_NORMAL_COLLECTION_NAME,
    LEVEL_VISUALS_HIERRARHY_COLLECTION_NAME,
    LEVEL_VISUALS_PROGRESSIVE_COLLECTION_NAME,
    LEVEL_VISUALS_LOD_COLLECTION_NAME,
    LEVEL_VISUALS_TREE_PM_COLLECTION_NAME,
    LEVEL_VISUALS_TREE_ST_COLLECTION_NAME
)

LEVEL_VISUALS_COLLECTION_NAMES_TABLE = {
    'normal': LEVEL_VISUALS_NORMAL_COLLECTION_NAME,
    'hierrarhy': LEVEL_VISUALS_HIERRARHY_COLLECTION_NAME,
    'progressive': LEVEL_VISUALS_PROGRESSIVE_COLLECTION_NAME,
    'lod': LEVEL_VISUALS_LOD_COLLECTION_NAME,
    'tree_pm': LEVEL_VISUALS_TREE_PM_COLLECTION_NAME,
    'tree_st': LEVEL_VISUALS_TREE_ST_COLLECTION_NAME
}

LIGHT_NAME = 'light'
GLOW_NAME = 'glow'
SECTOR_NAME = 'sector'
PORTAL_NAME = 'portal'
